### ISSUE TITLE
toListUntilChanged(Func1<? super T,? extends U> keySelector) 

### ISSUE THREAD

**Issue by thomasnield** [davidmoten/rxjava-extras#1]
Can we implement an overload for the `Transformers.toListUntilChanged()` that accepts a `Func1<? super T,? extends U> keySelector)`? That way you can choose what to distinct on just like the Observable's `distinct()` operator can...

**Comment by davidmoten** [comment]
That's in already and is called toListWhile().

**Comment by thomasnield** [comment]
Okay sorry, must have an older build at work...
