### ISSUE TITLE
rxkotlin-extras

### ISSUE THREAD

**Issue by thomasnield** [davidmoten/rxjava-extras#10]
Hi David, 

I am thinking of creating an `rxkotlin-extras` project that will express `rxjava-extras` as Kotlin extension functions for the `Observable<T>`. That way `lift()` and `compose()` do not have to be called in Kotlin code.

```kotlin
val source = Observable.create("Alpha","Beta","Gamma")
source.doOnFirst { println("First element is $it") }.subscribe { println(it) }
```

I wanted your blessing before I embarked on this possibly, or give you first chance to do it if you'd like to own it.

**Comment by davidmoten** [comment]
Hi Thomas, thanks for asking, sounds good, go for it!

**Comment by thomasnield** [comment]
Awesome thanks! I'll start it this week sometime.

**Comment by thomasnield** [comment]
FYI, project has been started here. Will probably take a few weeks before a release. 
https://github.com/thomasnield/rxkotlin-extras
