### ISSUE TITLE
ORACLE PROPRIETARY/CONFIDENTIAL inside util/ByteArrayOutputStreamNoCopyUnsynchronized.java

### ISSUE THREAD

**Issue by ShivrajKharvi** [davidmoten/rxjava-extras#36]
Hi Team,

I was just going through the code and found out that inside **com/github/davidmoten/util/ByteArrayOutputStreamNoCopyUnsynchronized.java** we can see  ORACLE PROPRIETARY/CONFIDENTIAL. Just wanted to know now that project is open sourced is it still required? Can we remove it?

**Comment by davidmoten** [comment]
Hmm, that's a simple enough class. I'll clean it up.

**Comment by davidmoten** [comment]
I've removed those bits. This is a trivial class that I can completely rewrite if required.

**Comment by davidmoten** [comment]
0.8.0.19 is on Maven Central with this change.
